# Shadowrocket: 2026-05-15 00:16:41
[General]

update-url = https://raw.githubusercontent.com/nncat01/sr-conf-ru/refs/heads/main/DirectRU_D.conf

# Include other configuration 
# include =

# IPv6 settings
ipv6 = false
prefer-ipv6 = false

# DNS settings
dns-direct-system = false
dns-fallback-system = false
dns-direct-fallback-proxy = true
dns-server = https://dns.comss.one/dns-query,https://cloudflare-dns.com/dns-query,https://dns.google/dns-query
fallback-dns-server = tls://77.88.8.88:853,https://safe.dot.dns.yandex.net/dns-query,2a02:6b8::feed:bad,77.88.8.88,system
hijack-dns = :53
private-ip-answer = true

# Proxy settings
bypass-system = true
skip-proxy = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local,captive.apple.com
tun-excluded-routes = 10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.0.0.0/24,192.0.2.0/24,192.88.99.0/24,192.168.0.0/16,198.51.100.0/24,203.0.113.0/24,224.0.0.0/4,255.255.255.255/32,239.255.255.250/32
# tun-included-routes =
# always-real-ip = *
icmp-auto-reply = false
always-reject-url-rewrite = false
# udp-policy-not-supported-behaviour = REJECT

[Rule]
# BitTorrent = WARP (Beta)
# DST-PORT,6969,WARP AWG 2.0

# RU = DIRECT
GEOIP,RU,DIRECT
DOMAIN-SUFFIX,ru,DIRECT
DOMAIN-SUFFIX,рф,DIRECT
DOMAIN-SUFFIX,su,DIRECT
DOMAIN-KEYWORD,2gis,DIRECT
DOMAIN-KEYWORD,ozon,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Yandex/Yandex.list,DIRECT

# VK = DIRECT
IP-ASN,47541,DIRECT
IP-ASN,47764,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/VK/VK.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Mailru/Mailru.list,DIRECT

# IP detect = DIRECT
RULE-SET,https://raw.githubusercontent.com/misha-tgshv/shadowrocket-configuration-file/refs/heads/main/rules/domains_geo_detect.list,DIRECT
# Adds = BLOCK
# Coming soon

# YouTube = WARP
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/YouTube/YouTube.list,WARP AWG 2.0

# iOS, macOS, iPadOS, tvOS updates = BLOCK
DOMAIN-SUFFIX,mesu.apple.com,REJECT
DOMAIN-SUFFIX,gdmf.apple.com,REJECT
DOMAIN-SUFFIX,doh.dns.apple.com,REJECT

# Final rule = NL
FINAL,NL AWG 2.0
# ver. 1.2
